server {
    listen 80;
    server_name furidance.app www.furidance.app;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name furidance.app www.furidance.app;

    ssl_certificate /etc/letsencrypt/live/furidance.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/furidance.app/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://server:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
    try_files $uri $uri/ /index.html;
    add_header Content-Security-Policy "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; frame-src 'self' https://www.youtube.com;";
    }
}